apiVersion: v1
kind: Service
metadata:
  name: profile-app
spec:
  ports:
    - port: 8080
  selector:
    app: profile
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: profile-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: profile
spec:
  selector:
    matchLabels:
      app: profile
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - image: grafpoo/profile-app
        name: profile
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://profile-mysql:3306/profiles
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: Welcome123
        ports:
        - containerPort: 8080
          name: profile
        volumeMounts:
        - name: profile-persistent-storage
          mountPath: /home
      volumes:
      - name: profile-persistent-storage
        persistentVolumeClaim:
          claimName: profile-pv-claim
